# Copyright 2015 Google Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

branches:
  only:
    - master

language: php

matrix:
  include:
    - php: 5.5
      env: RUN_DEVSERVER_TESTS=true RUN_CS_FIXER=true
    - php: 5.6
    - php: hhvm
    - php: nightly

env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/credentials.json
    - GOOGLE_VERSION_ID=$TRAVIS_JOB_ID
    - PATH=${HOME}/gcloud/google-cloud-sdk/bin:${PATH}
    - PHP_CGI_PATH=/home/travis/.phpenv/shims/php-cgi

before_install:
  - php dump_credentials.php
  - testing/install_test_deps.sh

script:
  # run php-cs-fixer
  - if [ ! -z $RUN_CS_FIXER ]; then
      ./php-cs-fixer fix --dry-run --diff --config-file=.php_cs .;
    fi
  # run bigquery tests
  - pushd bigquery/api
  - composer install
  - phpunit
  - popd
  # run datastore tests
  - pushd datastore
  - composer install
  - phpunit
  - popd
  # run pubsub tests
  - pushd pubsub
  - composer install
  - phpunit
  - popd
  # run storage tests
  - pushd storage/api
  - composer install
  - phpunit
  - popd
  # run appengine storage tests
  - pushd appengine/standard/storage
  - composer install
  - phpunit
  - popd
  # run mailgun tests
  - pushd appengine/standard/mailgun
  - composer install
  - phpunit
  - popd
  # run mailjet tests
  - pushd appengine/standard/mailjet
  - composer install
  - phpunit
  - popd
  # run cloudsql tests
  - pushd appengine/standard/cloudsql
  - composer install
  - phpunit
  - popd
  # run appengine logging tests
  - pushd appengine/standard/logging
  - composer install
  - phpunit
  - popd
  # run compute engine logging tests
  - pushd compute/logging
  - composer install
  - phpunit
  - popd
  # run modules API tests
  - pushd appengine/standard/modules
  - composer install
  - env LOCAL_TEST_TARGETS='app.yaml backend.yaml' phpunit
  - popd
  # run users API tests
  - pushd appengine/standard/users
  - composer install
  - phpunit
  - popd

after_success:
  - composer require "satooshi/php-coveralls:^1.0"
  - travis_retry php vendor/bin/coveralls -v
